return {
    { Name = "Bandit", MinLevel = 1, MaxLevel = 14 },
    { Name = "Monkey", MinLevel = 15, MaxLevel = 29 },
    { Name = "Gorilla", MinLevel = 30, MaxLevel = 54 },
    { Name = "Pirate", MinLevel = 55, MaxLevel = 69 },
    { Name = "Brute", MinLevel = 70, MaxLevel = 89 },
    { Name = "Desert Bandit", MinLevel = 90, MaxLevel = 109 },
    { Name = "Desert Officer", MinLevel = 110, MaxLevel = 134 },
    { Name = "Snow Bandit", MinLevel = 135, MaxLevel = 159 },
    { Name = "Snowman", MinLevel = 160, MaxLevel = 189 },
    { Name = "Chief Petty Officer", MinLevel = 190, MaxLevel = 209 },
    { Name = "Sky Bandit", MinLevel = 210, MaxLevel = 249 },
    { Name = "Dark Master", MinLevel = 250, MaxLevel = 299 },
    { Name = "Toga Warrior", MinLevel = 300, MaxLevel = 374 },
    { Name = "Gladiator", MinLevel = 375, MaxLevel = 399 },
    { Name = "Military Soldier", MinLevel = 400, MaxLevel = 449 },
    { Name = "Military Spy", MinLevel = 450, MaxLevel = 499 },
    { Name = "Fishman Warrior", MinLevel = 500, MaxLevel = 549 },
    { Name = "Fishman Commando", MinLevel = 550, MaxLevel = 624 },
    { Name = "Warden", MinLevel = 625, MaxLevel = 649 },
    { Name = "Chief Warden", MinLevel = 650, MaxLevel = 674 },
    { Name = "Swan", MinLevel = 675, MaxLevel = 699 },
    { Name = "Magma Marine", MinLevel = 700, MaxLevel = 724 }
}
